// Square
export const LOAD_CARD_LIST = 'LOAD_CARD_LIST';
export const LOAD_BANNER = 'LOAD_BANNER';
export const UPDATE_CARD_LIST = 'UPDATE_CARD_LIST';
export const UPDATE_BANNER = 'UPDATE_BANNER';
// Me
export const LOAD_MY_CARD_LIST = 'LOAD_MY_CARD_LIST';
export const UPDATE_MY_CARD_LIST = 'UPDATE_MY_CARD_LIST';