// Square
export const LOAD_CARD_LIST = 'LOAD_CARD_LIST';
export const LOAD_BANNER = 'LOAD_BANNER';
export const UPDATE_CARD_LIST = 'UPDATE_CARD_LIST';
export const UPDATE_BANNER = 'UPDATE_BANNER';
// Me
export const LOAD_MY_CARD_LIST = 'LOAD_MY_CARD_LIST';
export const UPDATE_MY_CARD_LIST = 'UPDATE_MY_CARD_LIST';
export const LOAD_MY_SHOP = 'LOAD_MY_CARD_LIST';
export const UPDATE_MY_SHOP = 'UPDATE_MY_SHOP';
// Message
export const LOAD_FOLLOW_LIST = 'LOAD_FOLLOW_LIST'
export const UPDATE_FOLLOW_LIST = 'UPDATE_FOLLOW_LIST'
export const LOAD_NOTICE_LIST = 'LOAD_NOTICE_LIST'
export const UPDATE_NOTICE_LIST = 'UPDATE_NOTICE_LIST'